[package]

name = "rustfmt"
version = "0.0.1"
authors = ["Nicholas Cameron <nrc@ncameron.org>"]
description = "Tool to find and fix Rust formatting issues"
repository = "https://github.com/nick29581/rustfmt"
readme = "README.md"
license = "Apache-2.0/MIT"

[dependencies]
toml = "0.1.20"
rustc-serialize = "0.3.14"
unicode-segmentation = "0.1.2"
regex = "0.1.41"
term = "0.2.11"
strings = { version = "0.0.1", git = "https://github.com/nrc/strings.rs.git" }
diff = { git = "https://github.com/utkarshkukreti/diff.rs.git" }

[dev-dependencies]
