[workspace]
members = [
    "git-rustfmt",
    "rustfmt-config",
    "rustfmt-core",
    "rustfmt-format-diff",
]

[patch.crates-io]
rustfmt-config = { path = "rustfmt-config" }
rustfmt-core = { path = "rustfmt-core" }
