[package]

name = "rustfmt"
version = "0.1.0"
authors = ["Nicholas Cameron <ncameron@mozilla.com>", "Marcus Klaas <mail@marcusklaas.nl>", "The Rustfmt contributors"]
description = "Tool to find and fix Rust formatting issues"
repository = "https://github.com/rust-lang-nursery/rustfmt"
readme = "README.md"
license = "Apache-2.0/MIT"
include = ["src/*.rs", "Cargo.toml"]

[dependencies]
toml = "0.1.20"
rustc-serialize = "0.3.14"
unicode-segmentation = "0.1.2"
regex = "0.1.41"
term = "0.2.11"
strings = "0.0.1"
diff = "0.1.7"
syntex_syntax = "0.23.0"
log = "0.3.2"
env_logger = "0.3.1"
getopts = "0.2"
