[package]

name = "rustfmt"
version = "0.0.1"
authors = ["Nicholas Cameron <nrc@ncameron.org>"]
description = "tool to find and fix Rust formatting issues"
repository = "https://github.com/nick29581/rustfmt"
readme = "README.md"
license = "Apache-2.0/MIT"

#[dependencies.reprint]
#reprint = "0.0.1"
#path = "/home/ncameron/reprint"

[[bin]]
name = "rustfmt"
path = "src/mod.rs"
