[package]

name = "rustfmt"
version = "0.9.0"
authors = ["Nicholas Cameron <ncameron@mozilla.com>", "The Rustfmt developers"]
description = "Tool to find and fix Rust formatting issues"
repository = "https://github.com/rust-lang-nursery/rustfmt"
readme = "README.md"
license = "Apache-2.0/MIT"
include = ["src/*.rs", "Cargo.toml", "build.rs", "LICENSE-*"]
build = "build.rs"
categories = ["development-tools"]

[lib]
doctest = false

[features]
default = ["cargo-fmt"]
cargo-fmt = []

[dependencies]
toml = "0.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
unicode-segmentation = "1.0.0"
regex = "0.2"
term = "0.4"
strings = "0.1"
diff = "0.1"
log = "0.3"
env_logger = "0.4"
getopts = "0.2"

[target.'cfg(unix)'.dependencies]
libc = "0.2.11"

[target.'cfg(windows)'.dependencies]
kernel32-sys = "0.2.2"
winapi = "0.2.7"
