[package]

name = "rustfmt"
version = "0.0.1"
authors = ["Nicholas Cameron <nrc@ncameron.org>"]
description = "Tool to find and fix Rust formatting issues"
repository = "https://github.com/nick29581/rustfmt"
readme = "README.md"
license = "Apache-2.0/MIT"
build = "build.rs"

[dependencies.strings]
strings = "0.0.1"
git = "https://github.com/nrc/strings.rs.git"

[dev-dependencies]
diff = "0.1.0"
toml = "0.1.20"
