extend = ".cargo/Makefile.toml"

[tasks.install]
command = "cargo"
args = [
  "install",
  "--path",
  ".",
  "--force",
  "--locked",
]

[tasks.test-all]
run_task = { name = ["test", "test-ignored"] }

[tasks.test-ignored]
command = "cargo"
args = [
  "test",
	"--",
	"--ignored",
]
