# This Makefile.toml defines common tasks and settings used in the rustfmt project.

[env]
CFG_RELEASE = { value = "nightly", condition = { env_not_set = ["CFG_RELEASE"] } }
CFG_RELEASE_CHANNEL = { value = "nightly", condition = { env_not_set = ["CFG_RELEASE_CHANNEL"] } }

[tasks.b]
alias = "build"

[tasks.c]
alias = "check"

[tasks.t]
alias = "test"
